server:
  port: 8086

spring:
  application:
    name: simulator-service
  profiles:
    active: local
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

app:
  topic:
    order-start: production.started
    inventory-deduct: inventory.deduct
    line-fault: line.fault

resilience4j:
  circuitbreaker:
    instances:
      lineService:
        base-config: default
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s   # ✅ 단위 명시
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: simulator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.autonix.simulator_service.dto.OrderStartedEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # ✅ local용

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: simulator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer   # ✅ 추가
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer   # ✅ 추가
      properties:
        spring.json.trusted.packages: "*"   # ✅ 추가
        spring.json.value.default.type: com.autonix.simulator_service.dto.OrderStartedEvent   # ✅ 추가

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/   # ✅ docker용 호스트명