server:
  port: 8086

spring:
  application:
    name: simulator-service
  profiles:
    active: local
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.add.type.headers]": false

app:
  topic:
    order-start: production.started
    inventory-deduct: inventory.deduct
    line-fault: line.fault

resilience4j:
  circuitbreaker:
    instances:
      lineService:
        base-config: default
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s   # ✅ 단위 명시
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: simulator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.autonix.simulator_service.dto.OrderStartedEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # ✅ local용

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: simulator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.autonix.simulator_service.dto.OrderStartedEvent
  cloud:
    openfeign:
      client:
        config:
          line-service:
            url: http://line-service:8083
          inventory-service:
            url: http://inventory-service:8084
          shipping-service:
            url: http://shipping-service:8085

eureka:
  client:
    enabled: false   # Eureka 서버 없는 환경에서 직접 URL로 Feign 호출