server:
  port: 8084

spring:
  application:
    name: simulator-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: simulator-group
      auto-offset-reset: earliest
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      lineService: # 서비스 이름 (어노테이션에서 사용)
        base-config: default
    configs:
      default:
        registerHealthIndicator: true # 헬스체크에 표시
        slidingWindowSize: 10 # 최근 10번의 호출을 통계에 사용
        failureRateThreshold: 50 # 실패율 50% 이상일 때 서킷 오픈
        waitDurationInOpenState: 10000 # 서킷이 열린 후 다시 시도하기까지 대기시간(10초)
        permittedNumberOfCallsInHalfOpenState: 3 # 반개방 상태에서 허용할 호출 수
        slidingWindowType: COUNT_BASED